pipeline:
  name: Build Assignment
  identifier: Build_Assignment_1757001150914
  projectIdentifier: Demo
  orgIdentifier: default
  stages:
    - stage:
        name: Build Nginx
        identifier: Build_Nginx
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerReg
                    repo: linkon19/nginx
                    tags:
                      - Nginx
                    buildArgs:
                      NGINX_VERSION: <+stage.variables.nginx_version>
              - step:
                  type: AquaTrivy
                  name: Scan Image with Trivy
                  identifier: Scan_Image_with_Trivy
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    connectorRef: account.DockerReg
                    image:
                      type: docker_v2
                      tag: Nginx
                      name: linkon19/nginx
        variables:
          - name: nginx_version
            type: String
            description: ""
            required: true
            value: <+input>.executionInput().default(1.25.3)
  properties:
    ci:
      codebase:
        connectorRef: Github
        repoName: Assignment
        build: <+input>
