pipeline:
  name: Build Assignment
  identifier: Build_Assignment_1757001150914
  projectIdentifier: Demo
  orgIdentifier: default
  stages:
    - stage:
        name: Build Nginx
        identifier: Build_Nginx
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerReg
                    repo: linkon19/nginx
                    tags:
                      - Nginx
        variables:
          - name: nginx_version
            type: String
            description: ""
            required: true
            value: <+input>.executionInput().default(1.25.3)
  properties:
    ci:
      codebase:
        connectorRef: Github
        repoName: Assignment
        build: <+input>
